version: '3.8'

services:
  mysql:
    image: mysql:8
    restart: always
    container_name: mysql_nest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: smart_lockers
    ports:
      - '3309:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
